# Generated by Django 4.0.4 on 2022-04-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inProgram', models.CharField(choices=[('', 'Select One'), ('cse', 'CSE'), ('eee', 'EEE'), ('civil', 'Civil'), ('english', 'English'), ('buisness', 'Buisness'), ('mechanical', 'Mechanical')], default='', max_length=50, verbose_name='Program')),
                ('shift', models.CharField(choices=[('', 'Select One'), ('morning', 'Morning'), ('evening', 'Evening')], max_length=50, verbose_name='Shift')),
                ('session', models.CharField(choices=[('sumer_2024', 'Summer 2024')], default='summer_2024', max_length=50, verbose_name='Session')),
                ('section', models.CharField(choices=[('', 'Select One'), ('a', 'A'), ('b', 'B')], default='', max_length=50, verbose_name='Section')),
                ('sName', models.CharField(max_length=50, verbose_name='Student Name')),
                ('cNum', models.CharField(max_length=50, verbose_name='Contract NBumber')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('', 'Select One'), ('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='Gender')),
                ('bCert', models.CharField(max_length=50, verbose_name='Birth Certificate/NID number')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Student photo')),
                ('religion', models.CharField(choices=[('', 'Select One'), ('islam', 'Islam'), ('cristian', 'Cristian'), ('hindu', 'Hindu')], default='', max_length=50, verbose_name='Religion')),
                ('doBirth', models.CharField(max_length=50, verbose_name='Date of Birth')),
                ('pAds', models.CharField(max_length=50, verbose_name='Present address')),
                ('bGroup', models.CharField(choices=[('', 'Select One'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='', max_length=50, verbose_name='Blood Group')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('quota', models.CharField(choices=[('', 'Select One'), ('none', 'None'), ('disabled', 'Disablied'), ('freedom', 'Freedom Fighter')], default='', max_length=50, verbose_name='Quota')),
                ('fName', models.CharField(max_length=50, verbose_name='Father Name')),
                ('fcNum', models.CharField(max_length=50, verbose_name='Father phone no.')),
                ('fOccu', models.CharField(max_length=50, verbose_name='Father occupation')),
                ('fEmail', models.EmailField(blank=True, max_length=254, verbose_name='Father Email')),
                ('mName', models.CharField(max_length=50, verbose_name='Mother Name')),
                ('mcNum', models.CharField(max_length=50, verbose_name='Mother phone no.')),
                ('mOccu', models.CharField(max_length=50, verbose_name='Mother occupation')),
                ('mEmail', models.EmailField(blank=True, max_length=254, verbose_name='Mother Email')),
                ('eTitle1', models.CharField(choices=[('', 'Select One'), ('ssc', 'SSC'), ('dakhil', 'Dakhil'), ('vocational', 'Vocational')], default='', max_length=50, verbose_name='Exam Title')),
                ('board1', models.CharField(choices=[('', 'Select One'), ('dhaka', 'Dhaka'), ('cumilla', 'Cumilla'), ('barishal', 'Barishal'), ('madrasha', 'Madrasha'), ('bteb', 'BTEB')], default='', max_length=50, verbose_name='Board')),
                ('eGroup1', models.CharField(max_length=50, verbose_name='Group')),
                ('bRoll1', models.CharField(default='', max_length=50, verbose_name='Board Roll')),
                ('eResult1', models.CharField(max_length=50, verbose_name='Result')),
                ('pYear1', models.CharField(default='', max_length=50, verbose_name='Pass Year')),
                ('insName1', models.CharField(max_length=50, verbose_name='Institute Name')),
                ('eTitle2', models.CharField(choices=[('', 'Select One'), ('hsc', 'HSC'), ('alim', 'Almin'), ('diploma', 'Diploma')], default='', max_length=50, verbose_name='Exam Title')),
                ('board2', models.CharField(choices=[('', 'Select One'), ('dhaka', 'Dhaka'), ('cumilla', 'Cumilla'), ('barishal', 'Barishal'), ('madrasha', 'Madrasha'), ('bteb', 'BTEB')], max_length=50, verbose_name='Board')),
                ('eGroup2', models.CharField(max_length=50, verbose_name='Group')),
                ('bRoll2', models.CharField(default='', max_length=50, verbose_name='Board Roll')),
                ('eResult2', models.CharField(max_length=50, verbose_name='Result')),
                ('pYear2', models.CharField(default='', max_length=50, verbose_name='Pass Year')),
                ('insName2', models.CharField(blank=True, max_length=50, verbose_name='Institute Name')),
                ('dName1', models.CharField(blank=True, max_length=50, verbose_name='Degree Name')),
                ('uBoard1', models.CharField(blank=True, max_length=50, verbose_name='Board/University')),
                ('mGroup1', models.CharField(blank=True, max_length=50, verbose_name='Institute Name')),
                ('bRoll3', models.CharField(blank=True, default='', max_length=50, verbose_name='Board Roll')),
                ('eResult3', models.CharField(blank=True, max_length=50, verbose_name='Result')),
                ('pYear3', models.CharField(blank=True, default='', max_length=50, verbose_name='Passing Year')),
                ('insName3', models.CharField(blank=True, max_length=50, verbose_name='Institute Name')),
                ('dName2', models.CharField(blank=True, max_length=50, verbose_name='Degree Name')),
                ('uBoard2', models.CharField(blank=True, max_length=50, verbose_name='Board/University')),
                ('mGroup2', models.CharField(blank=True, max_length=50, verbose_name='Institute Name')),
                ('eResult4', models.CharField(blank=True, max_length=50, verbose_name='Result')),
                ('pYear4', models.CharField(blank=True, default='', max_length=50, verbose_name='Passing Year')),
                ('insName4', models.CharField(blank=True, max_length=50, verbose_name='Institute Name')),
            ],
        ),
    ]
