# Generated by Django 4.0.4 on 2022-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
