# Generated by Django 4.0.4 on 2022-04-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0002_personalinfo_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='barcode',
            new_name='qr_code',
        ),
    ]
